### ISSUE TITLE
Easy way to manipulate individual hcl axes?

### ISSUE THREAD

**Issue by hadley** [EmilHvitfeldt/prismatic#20]
Something like this maybe:

```R
modify_hcl <- function(x, h, c, l) {
  hcl <- as.data.frame(farver::decode_colour(x, to = "hcl"))

  if (!missing(h)) {
    h <- eval(substitute(h), envir = hcl)
  } else {
    h <- hcl$h
  }
  if (!missing(c)) {
    c <- eval(substitute(c), envir = hcl)
  } else {
    c <- hcl$c
  }
  if (!missing(l)) {
    l <- eval(substitute(l), envir = hcl)
  } else {
    l <- hcl$l
  }
  
  farver::encode_colour(cbind(h, c, l), from = "hcl")
}
```

Idea is to make it easy to do (e.g.) `modify_hcl(x, h = 25)` or `modify_hcl(x, h = h + 10)`

**Comment by EmilHvitfeldt** [comment]
I was waiting for someone to suggest this, so now it is time :) 

I like `eval` steps. Design-wise I think I'm going to split this function (and others) so we have `modify_hue()`, `modify_chroma()` etc etc. I would properly still keep `modify_hcl()` as shorthand, as I think it is important that the function names reflect what we are working with.

**Comment by hadley** [comment]
I think having individual functions would be a substantial decrease in usability.

**Comment by EmilHvitfeldt** [comment]
Could you expand on your reasoning?

Adding

- `modify_hue()`
- `modify_chroma()`
- `modify_ luminance()`
- `modify_hcl()`

vs

- `modify_hcl()`

Is it because it would add many more functions with redundancy?

**Comment by hadley** [comment]
Right, this is a lot of typing:

```R
x %>% 
  modify_hue(50) %>%
  modify_chroma(10)
```

is a lot of typing compared to:

```R
x %>% modify_colour(h = 50, c = 10)
``

I think it's reasonable to assume that people know what `h`, `c`, and `l` stand for in a colour manipulation package.

Also note that these two operations don't necessarily produce the same colour:

```R
x %>% 
  modify_hue(50) %>%
  modify_chroma(10)

x %>% 
  modify_chroma(10) %>%
  modify_hue(50)
```

Really you want to do all the modifications in one transformation to hcl space, rather than going back and forth to and from rgb multiple times.

**Comment by EmilHvitfeldt** [comment]
I happened! It took a while for me to get around to it

**Comment by hadley** [comment]
Thanks!
