### ISSUE TITLE
Print color dataframes

### ISSUE THREAD

**Issue by trang1618** [EmilHvitfeldt/prismatic#25]
Thank you for such a nice package, @EmilHvitfeldt! 🌈 

I wonder if there is plan for adding a pretty_print() method for dataframes of colors?

**Comment by EmilHvitfeldt** [comment]
Can you provide a reprex of what you want? 🌈

**Comment by trang1618** [comment]
Ah yes. Thank you for the quick response!

So my hope is that, starting out with matrices, pretty_print() would print a matrix of hex values similar to how R would print a matrix but with the added background color. Currently, it seems to print all the colors but not in the matrix layout. Perculiarly, prismatic::color() adds "FF" at the end of these hex codes.

``` r
library(crayon)
library(prismatic)

dat <- matrix(rainbow(12), nrow = 4)
dat
#>      [,1]      [,2]      [,3]     
#> [1,] "#FF0000" "#00FF00" "#0000FF"
#> [2,] "#FF8000" "#00FF80" "#8000FF"
#> [3,] "#FFFF00" "#00FFFF" "#FF00FF"
#> [4,] "#80FF00" "#0080FF" "#FF0080"
prismatic:::pretty_print(dat)
#> #FF0000 #FF8000 #FFFF00 #80FF00 #00FF00 #00FF80 #00FFFF #0080FF #0000FF #8000FF #FF00FF #FF0080
prismatic::color(dat)
#> <colors>
#> #FF0000FF #FF8000FF #FFFF00FF #80FF00FF #00FF00FF #00FF80FF #00FFFFFF #0080FFFF #0000FFFF #8000FFFF #FF00FFFF #FF0080FF
```
Screenshot:
![prismatic-ex](https://user-images.githubusercontent.com/1679452/148008921-28fbef2c-d318-4956-b1de-4d7e674fabeb.png)

And it seems that there's currently no method for pretty printing data.frame:
``` r
prismatic:::pretty_print(data.frame(dat))
#> Error in crayon::make_style(best_contrast(x), bg = FALSE): is.character(style) && length(style) == 1 || is_rgb_matrix(style) &&  .... is not TRUE
prismatic::color(data.frame(dat))
#> Error in prismatic::color(data.frame(dat)): `col` must not be a list.
```

Thanks again for taking a look!



<sup>Created on 2022-01-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by EmilHvitfeldt** [comment]
Hey @trang1618, that does sound cool. Unfortunately I'm not quite sure I'm able to do it. matrices and data.frames are a different beast I'm not familiar enough with with respect to the way I'm doing the coloring.

If you want I can help you write a hacky `pretty_print_matrix()`

**Comment by trang1618** [comment]
Ah I see! Thank you for taking a look @EmilHvitfeldt! I think a hacky `pretty_print_matrix()` would be helpful, but I don't want you to have to spend too much time on it, so please feel free to close the issue.
