### ISSUE TITLE
Use crayon for printing if available

### ISSUE THREAD

**Issue by thomasp85** [EmilHvitfeldt/prismatic#4]
One thing that could be super neat would be to use crayon for colouring the background during printing. You could simply use it if it was available so you'd only need to have it in suggests

**Comment by EmilHvitfeldt** [comment]
here it is! In all its glory!

<img width="858" alt="sceenshot" src="https://user-images.githubusercontent.com/14034784/65470487-42a5e980-de20-11e9-9c32-b2d97643e53a.png">

**Comment by thomasp85** [comment]
Fantastic
