### ISSUE TITLE
Feature request: UK spelling for colour

### ISSUE THREAD

**Issue by njtierney** [EmilHvitfeldt/prismatic#5]
Thanks for making this! Looks great.

Would it be possible to have `colour` as an alias for `color` in this package?

**Comment by EmilHvitfeldt** [comment]
Sure thing!

**Comment by njtierney** [comment]
Thanks!

**Comment by EmilHvitfeldt** [comment]
would you also want `clr_greyscale()` as alias for `clr_grayscale()`?

**Comment by njtierney** [comment]
Sure! :)
